### ISSUE TITLE
替换不到位

### ISSUE THREAD

**Issue by gitzwt** [Singiu/wordban#1]
我的词库有14000多个,放txt文件里,然后加载为数组,也打印看过数组正常,当使用escape方法替换不到位,有好多词库里有的词都没替换

**Comment by Singiu** [comment]
能提供一下测试用例吗？

**Comment by gitzwt** [comment]
词库用的是 https://github.com/observerss/textfilter 里的keyword文件,
我的代码如下
        $str = file_get_contents('./keywords');//将整个文件内容读入到一个字符串中
        $str_encoding = mb_convert_encoding($str, 'UTF-8', 'UTF-8,GBK,GB2312,BIG5');//转换字符集（编码）
        $arr = explode(PHP_EOL, $str_encoding);//转换成数组
        //去除值中的空格
        foreach ($arr as &$row) $row = trim($row);
        unset($row);
        WordBan::load($arr);
        return WordBan::escape($text);

测试文字使用 'SB就是傻逼！fuck is a bad word!'  输出结果是部分替换,但查了词库里有SB,傻逼,fuck这些词

望大佬帮忙看下指点下

**Comment by Singiu** [comment]
发现如果词库中同时存在 “傻逼” 和 “傻逼靠” 时，程序会只认后者 “傻逼靠”。
我已经增加了词尾识别逻辑，这个问题已经修复，请将包程序更新至 1.1.1  :smile:
感谢你的反馈 :stuck_out_tongue_closed_eyes:
